'\" t
.\"     Title: akmos
.\"    Author: Andrew Romanenko <melanhit@gmail.com>
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: March, 2017
.\"    Manual: AKMOS CLI REFERENCE
.\"    Source: akmos 0.6
.\"  Language: English
.\"
.TH "AKMOS" "1" "March, 2017" "akmos 0.6" "AKMOS CLI REFERENCE"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
akmos \- sets of cryptography utils
.SH "SYNOPSIS"
.HP \w'\fBakmos\fR\ 'u
\fBakmos\fR {action} [options]
.SH "DESCRIPTION"
.PP
The
\fBakmos\fR
utility is used for encryption/decryption files and streams, compute message digests and other\&.
.PP
Here is the list of available actions:
.PP
\fBdgst\fR
.RS 4
calculate message digests
.RE
.PP
\fBenc\fR, \fBdec\fR
.RS 4
symmetric ciphering
.RE
.PP
\fBmac\fR
.RS 4
compute message authentication code
.RE
.PP
\fBhelp\fR
.RS 4
Print a short help
.RE
.SH "SYMMETRIC CIPHERING"
.SS ""
.HP \w'\fBakmos\ enc|dec\fR\ 'u
\fBakmos enc|dec\fR [\-a\ \fIalgo[:flag]\fR] [\-m\ \fImode\fR] [\-k\ \fIkeyfile\fR] [\-l\ \fIkeylen\fR] [\-p] [\-P\ \fIpassfile\fR] [\-i\ \fIiter\fR] [\-y] [\-V] [\-h] {input} {output}
.SS "Options"
.PP
.PP
\-a\ algo[:flag]
.RS 4
Crypto algorithm to use\&. By default is
\fBTwofish\fR
.sp
Supported FLAGS
.sp
\fB:ede\fR
flag put cipher into Encrypt\-Decrypt\-Encrypt mode (like 3DES)
.sp
\fB:eee\fR
flag put cipher into Encrypt\-Encrypt\-Encrypt mode
.sp
NOTE: TDEA not available with stream ciphers
.RE
.PP
\-m\ mode
.RS 4
Crypto mode to use\&. By default is
\fBCBC\fR
for block ciphers, and
\fBCTR\fR
for stream ciphers\&.
.RE
.PP
\-k\ keyfile
.RS 4
Specifies a file which contains the keyfile
.sp
NOTE: size of keyfile is limited by
\fB1 MiB\fR
.RE
.PP
\-p
.RS 4
Use a passphrase as a component of the keyfile
.RE
.PP
\-P\ passfile
.RS 4
Read passphrase from a file
.RE
.PP
\-l\ keylen
.RS 4
Key length (in bits) to use with the given crypto algorithm\&. By default is
\fB128\fR
bits
.RE
.PP
\-i\ iter
.RS 4
Number of iterations to use with PKCS#5v2 when processing passphrase component\&. By defualt is
\fB4096\fR\&.
.RE
.PP
\-y
.RS 4
Overwrite output file without promt
.RE
.PP
\-V
.RS 4
Display akmos version
.RE
.PP
\-h
.RS 4
Print a short help
.RE
.SS "Algorithms"
.PP
Supported symmetric crypto algorithms:
\fIAnubis\fR, \fIBlowfish\fR, \fIChacha\fR, \fICamellia\fR, \fICAST6\fR, \fIRC6\fR, \fIRijndael\fR, \fISalsa\fR, \fISEED\fR, \fISerpent\fR, \fITwofish\fR, \fIThreefish\-256\fR, \fIThreefish\-512\fR, \fIThreefish\-1024\fR
.SS "Modes"
.PP
Supported cipher modes:
.PP
\fBCBC\fR \- Cipher Block Chaining
.RS 4
.RE
.PP
\fBCFB\fR \- Cipher Feedback
.RS 4
.RE
.PP
\fBCTR\fR \- Counter
.RS 4
.RE
.PP
\fBECB\fR \- Electronic Codebook
.RS 4
.RE
.PP
\fBOFB\fR \- Output Feedback
.RS 4
.RE
.SS "Key length"
.PP
\fBAnubis\fR
.RS 4
\fI128\fR, \fI192\fR, \fI256\fR, \fI320\fR
.RE
.PP
\fBBlowfish\fR
.RS 4
\fI128\fR, \fI160\fR, \fI192\fR, \fI224\fR, \fI256\fR, \fI288\fR, \fI320\fR, \fI352\fR, \fI384\fR, \fI416\fR, \fI448\fR
.RE
.PP
\fBChacha\fR
.RS 4
\fI256\fR
.RE
.PP
\fBCamellia\fR
.RS 4
\fI128\fR, \fI192\fR, \fI256\fR
.RE
.PP
\fBCAST6\fR
.RS 4
\fI128\fR, \fI192\fR, \fI256\fR
.RE
.PP
\fBRC6\fR
.RS 4
\fI128\fR, \fI192\fR, \fI256\fR
.RE
.PP
\fBRijndael\fR
.RS 4
\fI128\fR, \fI192\fR, \fI256\fR
.RE
.PP
\fBSalsa\fR
.RS 4
\fI128\fR, \fI256\fR
.RE
.PP
\fBSEED\fR
.RS 4
\fI128\fR
.RE
.PP
\fBSerpent\fR
.RS 4
\fI128\fR, \fI192\fR, \fI256\fR
.RE
.PP
\fBThreefish\-256\fR
.RS 4
\fI256\fR
.RE
.PP
\fBThreefish\-512\fR
.RS 4
\fI512\fR
.RE
.PP
\fBThreefish\-1024\fR
.RS 4
\fI1024\fR
.RE
.PP
\fBTwofish\fR
.RS 4
\fI128\fR, \fI192\fR, \fI256\fR
.RE
.SH "HASHING"
.SS ""
.HP \w'\fBakmos\ dgst\fR\ 'u
\fBakmos dgst\fR [\-a\ \fIalgo\fR] [\-n\ \fIthreads\fR] [\-b] [\-V] [\-h] \fIinput\fR...
.SS "Options"
.PP
.PP
\-a\ algo
.RS 4
Digest algorithm to use\&. By default is
\fBSHA2\-256\fR
.RE
.PP
\-n\ threads
.RS 4
Number of the threads to process multiple inputs\&. By default is
\fB2\fR
.RE
.PP
\-b
.RS 4
Output result in binary format\&. By default use hexadecimal
.RE
.PP
\-V
.RS 4
Display akmos version
.RE
.PP
\-h
.RS 4
Print a short help
.RE
.SS "Algorithms"
.PP
Supported digest algorithms:
\fIRIPEMD\-160\fR, \fIRIPEMD\-256\fR, \fIRIPEMD\-320\fR, \fISHA1\fR, \fISHA2\-224\fR, \fISHA2\-256\fR, \fISHA2\-384\fR, \fISHA2\-512\fR, \fISHA3\-224\fR, \fISHA3\-256\fR, \fISHA3\-384\fR, \fISHA3\-512\fR, \fITIGER\fR, \fIWHIRLPOOL\fR
.SH "MESSAGE AUTHENTICATION CODE (MAC)"
.SS ""
.HP \w'\fBakmos\ mac\fR\ 'u
\fBakmos mac\fR [\-a\ \fIalgo\fR] [\-m\ \fImode\fR] [\-k\ \fIkeyfile\fR] [\-l\ \fIkeylen\fR] [\-p] [\-P\ \fIpassfile\fR] [\-b] [\-V] [\-h] \fIinput\fR...
.SS "Options"
.PP
.PP
\-m\ mode
.RS 4
MAC mode to use\&. By default is
\fBHMAC\fR
.RE
.PP
\-a\ algo
.RS 4
Algorithm to use\&. By default is
\fBSHA2\-256\fR
for
\fBHMAC\fR
mode
.RE
.PP
\-k\ keyfile
.RS 4
Specifies a file which contains the keyfile
.sp
NOTE: size of keyfile is limited by
\fB1 MiB\fR
.RE
.PP
\-p
.RS 4
Use a passphrase as a component of the keyfile
.RE
.PP
\-P\ passfile
.RS 4
Read passphrase from a file
.RE
.PP
\-l\ keylen
.RS 4
Key length (in bits) to use with the given algorithm\&.
.sp
NOTE: used in
\fBCBC\-MAC\fR
mode
.RE
.PP
\-b
.RS 4
Output computed MAC in raw (binary) form\&.
.RE
.PP
\-V
.RS 4
Display akmos version
.RE
.PP
\-h
.RS 4
Print a short help
.RE
.SS "Modes"
.PP
Supported MAC modes:
.PP
\fBHMAC\fR \- keyed\-Hash Message Authentication Code
.RS 4
.RE
.PP
\fBCBC\-MAC\fR \- Cipher Block Chaining Message Authentication Code
.RS 4
.RE
.PP
\fBCMAC\fR \- Cipher\-based Message Authentication Code
.RS 4
.RE
.SH "EXIT STATUS"
.PP
The
\fBakmos\fR
utility exits
\fB0\fR
on successful completion, and
\fB>0\fR
otherwise
.SH "AUTHOR"
.PP
\fBAndrew Romanenko\fR <\&melanhit@gmail\&.com\&>
.RS 4
.RE
